config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  
  resources :karina_photos, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get 'perfil', to: 'home#profile', as: :user_profile

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'karina_photos#index'
  
end

app/models/karina_photo.rb
class KarinaPhoto < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  validates :title, presence: true
  validates :description, presence: true
  validates :image, presence: true

end

app/controllers/karina_photos_controller.rb
class KarinaPhotosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_karina, only: [:new, :create, :edit, :update, :destroy]

  def index
    @karina_photos = KarinaPhoto.all
  end

  def show
    @karina_photo = KarinaPhoto.find(params[:id])
    @comment = Comment.new
  end

  def new
    @karina_photo = KarinaPhoto.new
  end

  def create
    @karina_photo = current_user.karina_photos.build(karina_photo_params)

    if @karina_photo.save
      redirect_to root_path, notice: 'Publicación creada con éxito'
    else
      render :new
    end
  end

  def edit
    @karina_photo = current_user.karina_photos.find(params[:id])
  end

  def update
    @karina_photo = current_user.karina_photos.find(params[:id])

    if @karina_photo.update(karina_photo_params)
      redirect_to root_path, notice: 'Publicación actualizada con éxito'
    else
      render :edit
    end
  end

  def destroy
    @karina_photo = current_user.karina_photos.find(params[:id])
    @karina_photo.destroy

    redirect_to root_path, notice: 'Publicación eliminada con éxito'
  end

  private

  def karina_photo_params
    params.require(:karina_photo).permit(:title, :description, :image)
  end

  def check_karina
    unless current_user.admin?
      redirect_to root_path, alert: 'No está autorizado para esta acción'
    end
  end
end

app/helpers/karina_photos_helper.rb
module KarinaPhotosHelper
end

app/views/karina_photos/_form.html.erb
<div class="container-new">   
    <%= form_for(@karina_photo, html: { multipart: true }) do |f| %>

        <%= render partial: "karina_photos/image", locals: { f: f, karina_photo: @karina_photo } %>

        <div class="form-field">
            <%= f.label :Título %>
            <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-field">
            <%= f.label :Descripción %>
            <%= f.text_area :description, class: "form-control" %>
        </div>

        <div class="form-actions">
            <%= f.submit 'Guardar', class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/karina_photos/_image.html.erb
<div data-controller="preview">
    <%= f.label :image, "Cargar Imagen", style: "display: block" %>

    <%= f.file_field :image,
                    direct_upload: true,
                    data: { preview_target: "input", action: "change->preview#preview" } %>

    <div class="image-preview-container">
        <% if @karina_photo.image.attached? %>
            <%= image_tag karina_photo.image, data: { preview_target: "preview" }, class: "image-preview" %>
        <% else %>
            <%= image_tag "", data: { preview_target: "preview" }, class: "image-preview" %>
        <% end %>
    </div>
</div>

app/views/karina_photos/edit.html.erb
<h1>Editar Publicación</h1>

<%= render 'form' %>

<%= link_to karina_photos_path, class: "back-link" do %>
<i class="fas fa-arrow-left"></i> Volver
<% end %>

app/views/karina_photos/index.html.erb
<!-- index.html.erb -->
<section class="portfolio">
    <div class="container">
        <h1 class="section-title py-5">Capturando Instantes</h1>
        <% if user_signed_in? && current_user.admin? %>
            <%= link_to 'Nueva Publicación', new_karina_photo_path, class: "btn btn-gradient mt-2 mb-5" %>
        <% end %>
        <div class="grid-container">
            <% @karina_photos.each do |karina_photo| %>
                <div class="grid-item">
                    <div class="portfolio-item">
                        <%= image_tag karina_photo.image, class: "img-fluid portfolio-img", alt: "Karina Photo" %>
                        <div class="portfolio-overlay">
                            <div class="title-container">
                                <h4 class="portfolio-title"><%= karina_photo.title %></h4>
                                <div class="btn-container">
                                    <%= link_to 'Ver detalle', karina_photo_path(karina_photo), class: "btn btn-detail" %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/karina_photos/new.html.erb
<div class="container-new">
    <h1>Nueva Publicación</h1>

    <%= render 'form' %>
</div>

    <%= link_to karina_photos_path, class: "back-link" do %>
    <i class="fas fa-arrow-left"></i> Volver
    <% end %>

app/views/karina_photos/show.html.erb
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card show-card">
                <%= image_tag @karina_photo.image, class: "card-img-top img-fluid rounded-top", alt: "Karina Photo" %>
                <div class="card-body">
                    <h2 class="show-card-title"><%= @karina_photo.title %></h2>
                    <p class="show-card-text"><%= @karina_photo.description %></p>
                </div>
                <% if user_signed_in? && current_user.admin? %>
                <div class="card-footer">
                    <div class="btns" role="group" aria-label="Actions">
                        <%= link_to 'Editar', edit_karina_photo_path(@karina_photo), class: "btn btn-edit" %>
                        <%= button_to 'Eliminar', @karina_photo, method: :delete, data: { confirm: 'Estás seguro?' }, class: "btn btn-delete" %>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

        <% if user_signed_in? %>
            <div class="add-comment my-4">
                <%= render partial: "comments/form", locals: { karina_photo: @karina_photo, comment: @comment } %>
            </div>
        <% else %>
            <div class="add-comment my-4">
            <p>Por favor, <%= link_to 'Inicia Sesión', new_user_session_path %> para agregar comentarios.</p>
            </div>
        <% end %>

        <div class="comments-container p-3">
            <% if @karina_photo.comments.present? %>
            <h3 class="mb-3">Comentarios</h3>
                <ul class="list-unstyled">
                    <% @karina_photo.comments.each do |comment| %>
                        <li class="media mb-4 comment">
                            <%= image_tag comment.user.avatar, class: 'avatar' %>
                            <div class="media-body comment-content">
                                <h5 class="mt-0 mb-1 user-name"><%= comment.user.name %></h5>
                                <small class="text-muted timestamp"><%= comment.created_at.strftime('%d de %B de %Y, %H:%M') %></small>
                                <p><%= comment.content %></p>
                                <% if comment.user == current_user %>
                                <div class="btns">
                                    <%= link_to 'Editar', edit_karina_photo_comment_path(@karina_photo, comment), class: 'btn btn-edit' %>
                                    <%= button_to 'Eliminar', karina_photo_comment_path(@karina_photo, comment), method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-delete' %>
                                </div>
                                <% end %>
                            </div>
                        </li>
                    <% end %>
                </ul>
            <% else %>
                <h4>¡Tu comentario será el primero!</h4>
            <% end %>
        </div>

            <%= link_to karina_photos_path, class: "back-link" do %>
            <i class="fas fa-arrow-left"></i> Volver
            <% end %>
        </div>
    </div>
</div>